# Generated by Django 5.1.1 on 2024-10-16 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_book_dislikes_remove_book_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Bookcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='main.book_category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='main.category'),
        ),
        migrations.CreateModel(
            name='audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Kitob nomi')),
                ('text', models.TextField(help_text='Kitob matnini yozing')),
                ('image', models.ImageField(upload_to='')),
                ('file', models.FileField(upload_to='')),
                ('price', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0, editable=False)),
                ('sold', models.PositiveIntegerField(default=0)),
                ('reg_date', models.DateField(auto_now_add=True)),
                ('Bookcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='main.book_category')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='main.category')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-reg_date'],
            },
        ),
    ]
