# Generated by Django 5.1.1 on 2024-10-18 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_book_bookcategory_alter_book_category_audio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'ordering': ['-reg_date'], 'verbose_name': 'audio', 'verbose_name_plural': 'audios'},
        ),
        migrations.AddField(
            model_name='book_category',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='main.category'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='text',
            field=models.TextField(help_text='Audio Kitob matnini yozing'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Audio Kitob nomi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='main.category'),
        ),
    ]
