# Generated by Django 5.1.1 on 2025-02-19 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_cartitem_favorite_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contant',
            name='phonenumber',
        ),
    ]
