# Generated by Django 5.1.1 on 2025-02-19 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_contant_phonenumber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contant',
            new_name='Comment',
        ),
    ]
